# Generated by Django 6.0.3 on 2026-09-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('UNDER_REVIEW', 'Under Clinical Review'), ('VALIDATED', 'Validated by Doctor')], default='COMPLETED', max_length=30)),
                ('demographics', models.JSONField(blank=True, default=dict)),
                ('prakriti_data', models.JSONField(blank=True, default=dict)),
                ('lifestyle_data', models.JSONField(blank=True, default=dict)),
                ('diet_data', models.JSONField(blank=True, default=dict)),
                ('symptoms_data', models.JSONField(blank=True, default=dict)),
                ('prakriti_scores', models.JSONField(blank=True, default=dict)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('shap_explanations', models.JSONField(blank=True, default=list)),
                ('lime_explanations', models.JSONField(blank=True, default=list)),
                ('rag_evidence', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_REVIEW', 'In Review'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_clinical_reviews', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_clinical_reviews', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinical.patientassessment')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
