# Generated by Django 6.0.3 on 2026-09-29 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(default='Personalized Ayurvedic Pathya Ahara Protocol', max_length=255)),
                ('duration', models.CharField(default='14 Days Pacing Cycle', max_length=100)),
                ('objective', models.TextField(blank=True)),
                ('generated_by', models.CharField(choices=[('AI', 'AI Generated'), ('DOCTOR', 'Doctor Authored'), ('AI_ASSISTED_DOCTOR', 'AI-Assisted Doctor Modified')], default='AI', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_DOCTOR_APPROVAL', 'Pending Doctor Approval'), ('ACTIVE', 'Active (Prescribed)'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('breakfast', models.JSONField(blank=True, default=dict)),
                ('mid_morning', models.JSONField(blank=True, default=dict)),
                ('lunch', models.JSONField(blank=True, default=dict)),
                ('evening', models.JSONField(blank=True, default=dict)),
                ('dinner', models.JSONField(blank=True, default=dict)),
                ('foods_to_include', models.JSONField(blank=True, default=list)),
                ('foods_to_avoid', models.JSONField(blank=True, default=list)),
                ('lifestyle_notes', models.JSONField(blank=True, default=list)),
                ('precautions', models.JSONField(blank=True, default=list)),
                ('doctor_notes', models.TextField(blank=True)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('knowledge_references', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_diet_plans', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_plans', to='clinical.patientassessment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diet_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('snapshot_data', models.JSONField(default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='clinical.dietplan')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='GENERAL', max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(blank=True, max_length=150)),
                ('patient_value', models.JSONField(blank=True, default=dict)),
                ('verified_value', models.JSONField(blank=True, default=dict)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified by Doctor'), ('CORRECTED', 'Corrected by Doctor')], default='UNVERIFIED', max_length=20)),
                ('doctor_note', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_verifications', to='clinical.patientassessment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_verifications', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'field_name'],
                'unique_together': {('patient', 'assessment', 'field_name')},
            },
        ),
    ]
