# Generated by Django 6.0.3 on 2026-09-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_auditlog_dietplan_dietplanversion_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('DOCTOR_VERIFIED_FIELD', 'Doctor Verified Field'), ('DOCTOR_CORRECTED_FIELD', 'Doctor Corrected Field'), ('AI_DIET_GENERATED', 'AI Diet Generated'), ('DOCTOR_EDITED_DIET', 'Doctor Edited Diet'), ('DIET_APPROVED', 'Diet Plan Approved'), ('DIET_REJECTED', 'Diet Plan Rejected'), ('DIET_ARCHIVED', 'Diet Plan Archived')], max_length=100),
        ),
    ]
