# Generated by Django 6.0.3 on 2026-09-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientverification',
            name='patient_value',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='patientverification',
            name='verified_value',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
