# Generated by Django 6.0.3 on 2026-10-10 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_alter_patientverification_patient_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('breakfast_reminder', models.BooleanField(default=True)),
                ('breakfast_time', models.CharField(default='07:45 AM', max_length=20)),
                ('mid_morning_reminder', models.BooleanField(default=True)),
                ('mid_morning_time', models.CharField(default='10:45 AM', max_length=20)),
                ('lunch_reminder', models.BooleanField(default=True)),
                ('lunch_time', models.CharField(default='01:15 PM', max_length=20)),
                ('evening_reminder', models.BooleanField(default=True)),
                ('evening_time', models.CharField(default='04:45 PM', max_length=20)),
                ('dinner_reminder', models.BooleanField(default=True)),
                ('dinner_time', models.CharField(default='07:30 PM', max_length=20)),
                ('water_reminders', models.BooleanField(default=True)),
                ('water_interval_hours', models.IntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MID_MORNING', 'Mid-Morning Snack'), ('LUNCH', 'Lunch'), ('EVENING', 'Evening Snack'), ('DINNER', 'Dinner')], max_length=30)),
                ('meal_name', models.CharField(max_length=255)),
                ('scheduled_time', models.CharField(default='08:00 AM', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('energy_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diet_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_meals', to='clinical.dietplan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'scheduled_time'],
                'unique_together': {('patient', 'date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meals_planned', models.IntegerField(default=5)),
                ('meals_completed', models.IntegerField(default=0)),
                ('meals_skipped', models.IntegerField(default=0)),
                ('water_intake_ml', models.IntegerField(default=0)),
                ('water_goal_ml', models.IntegerField(default=2500)),
                ('adherence_rate', models.FloatField(default=0.0)),
                ('energy_rating', models.IntegerField(blank=True, null=True)),
                ('wellness_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('patient', 'date')},
            },
        ),
    ]
